name: Tests

on: [push]

jobs:
  build:
    uses: tktech/python-standard/.github/workflows/test.yml@main
    with:
      use_poetry: true
      use_sphinx: true
      use_black: true
      python_version: '3.11'
      platform: 'ubuntu-latest'
      black_path: 'smartie'